SRCS = \
	src/decompress.c \
	src/ignore.c \
	src/log.c \
	src/main.c \
	src/options.c \
	src/print.c \
	src/scandir.c \
	src/search.c \
	src/util.c
OBJS = $(subst .c,.o,$(SRCS))

CFLAGS = -O2 -DPCRE_STATIC -DPTW32_STATIC_LIB -I /usr/local/include
LIBS = -lz -llzma -lpthread -lpcre -lshlwapi
TARGET = ag.exe

all : $(TARGET)

$(TARGET) : $(OBJS)
	gcc -static -o $@ $(OBJS) -L /usr/local/lib $(LIBS)

.c.o :
	gcc -c $(CFLAGS) -Isrc $< -o $@

clean :
	rm -f src/*.o $(TARGET)
